CREATE TABLE "plaid_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plaid_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"plaidItemId" text NOT NULL,
	"accessTokenEncrypted" text NOT NULL,
	"institutionId" text,
	"institutionName" text,
	"cursor" text,
	"status" text DEFAULT 'active' NOT NULL,
	"lastSyncedAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "plaid_accounts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plaid_accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"plaidItemId" bigint NOT NULL,
	"plaidAccountId" text NOT NULL,
	"name" text NOT NULL,
	"mask" text,
	"type" text NOT NULL,
	"subtype" text,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "budgets" ALTER COLUMN "userId" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "userId" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "merchants" ALTER COLUMN "userId" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "plaid_items" ADD CONSTRAINT "plaid_items_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plaid_accounts" ADD CONSTRAINT "plaid_accounts_plaidItemId_plaid_items_id_fk" FOREIGN KEY ("plaidItemId") REFERENCES "public"."plaid_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "plaid_items_userId_idx" ON "plaid_items" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "plaid_items_plaidItemId_key" ON "plaid_items" USING btree ("plaidItemId");--> statement-breakpoint
CREATE INDEX "plaid_accounts_plaidItemId_idx" ON "plaid_accounts" USING btree ("plaidItemId");--> statement-breakpoint
CREATE UNIQUE INDEX "plaid_accounts_plaidAccountId_key" ON "plaid_accounts" USING btree ("plaidAccountId");